# Generated by Django 4.2.6 on 2023-10-12 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Passwords',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_name', models.CharField(max_length=100)),
                ('url', models.URLField()),
                ('username', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('password', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('TECH', 'Technology'), ('NONE', 'No category'), ('BIZ', 'Business'), ('EMAIL', 'Email'), ('ENT', 'Entertainment'), ('FIN', 'Finance'), ('GAMES', 'Games'), ('NEWS', 'News'), ('OTHER', 'Other'), ('SHOP', 'Shopping'), ('SOCIAL', 'Social media'), ('SPORTS', 'Sports'), ('TECH', 'Tech'), ('TRAVEL', 'Travel'), ('UTIL', 'Utilities')], default='No Category', max_length=100)),
            ],
        ),
    ]
