# Generated by Django 4.1.2 on 2022-10-20 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0002_remove_passwords_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwords',
            name='password',
            field=models.CharField(max_length=2000),
        ),
    ]
