# Generated by Django 4.1.2 on 2022-10-21 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0005_alter_passwords_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwords',
            name='password',
            field=models.CharField(max_length=100),
        ),
    ]
